"*.{js,ts}":
  - cspell lint --no-must-find-files --files
  - prettier --write --ignore-unknown
  - eslint --fix --max-warnings=0
"*.ts":
  - tsc-files --noEmit
"*.md":
  - cspell lint --no-must-find-files --files
