name: Call the CLI testing
on: pull_request


jobs:
  cli_test_linux_amd64:
    name: CLI tests on linux
    uses: ./.github/workflows/test-cli.yml
    permissions:
        contents: read
    with:
        name: build_linux_amd64
        runner: matterlabs-ci-runner

  cli_test_windows:
    name: CLI tests on Windows
    uses: ./.github/workflows/test-cli.yml
    permissions:
        contents: read
    with:
        name: build_windows_amd64
        runner: windows-2022-github-hosted-16core
    
  cli_test_macos_amd64:
    name: CLI tests on macOS
    uses: ./.github/workflows/test-cli.yml
    permissions:
        contents: read
    with:
        name: build_macos_amd64
        runner: macos-12-large
